#!/bin/bash
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

#test "" = "$(grep '^Signed-off-by: ' "$1" |
#	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
#	echo >&2 Duplicate Signed-off-by lines.
#	exit 1
#}

if [ $# -eq 0 ]
then
  echo "Hook para validacao de mensagens do git."
  echo "Para aplica-lo ao seu projeto execute:"
  echo "ln -s $0 <Dir do seu projeto>/.git/hooks/commit-msg"
  echo ""
  echo "Verificacoes: "
  cat $0 | grep "^#--- " | sed  "s/^#--//"
  exit 1
fi

#--- Insere a issue automaticamente
# Para usar recurso:
# 1. Crie um arquivo com o nome da issue:
#   echo "PROJ-123" > /tmp/arquivo
# 2. Atribua o caminho do arquivo na variavel de ambiente JIRA_HOOK_ISSUE_FILE
#   export JIRA_HOOK_ISSUE_FILE="/tmp/arquivo"
if [ -n "$JIRA_HOOK_ISSUE_FILE" ] && [ -f $JIRA_HOOK_ISSUE_FILE ]
then
  ISSUE=`cat $JIRA_HOOK_ISSUE_FILE`
  if [ -n "$ISSUE" ]
  then
    TMP_MSG=/tmp/$$-jirahook.tmp
    echo -n " #$ISSUE - " > $TMP_MSG
    cat $1 >> $TMP_MSG
    cp $TMP_MSG $1
  fi
fi

#--- Verifica se a mensagem contem o numero da issue
bldred='\e[1;31m' # Red
bldylw='\e[1;33m' # Yellow
txtblu='\e[0;34m' # Blue
txtrst='\e[0m'    # Text Reset
grep -w "#[A-Z0-9]\{1,\}-[0-9]\{1,\}" $1 > /dev/null || {
  echo -en $bldred
  echo "Noooooooo!!!"
  echo "COMMIT NAO EFETUADO!"
  echo -en $bldylw
  echo "Ae fera! Coloca a issue ai! Formato #SEUPROJETO-999"
  echo -en $txtblu
  echo "Se não quiser colocar mesmo, faça o commit com a opcao --no-verify"
  echo -en $txtrst
  exit 1
}

