"Customizações Cassiano
set vb
set ts=2
set sw=2
set sts=2
set ai
set cin
set et
set si
set sta
if has("gui_running")
  set lines=50
  set columns=120
  "set gfn=Lucida\ Console:h9
  color darkblue
endif

"Teclas personalizadas
"Aplicar sintaxe Linguagem C
map <F2> :set syn=c<Enter>
imap <F2> <ESC>:set syn=c<Enter>i

"Aplicar sintaxe Shell Script
map <S-F2> :set syn=sh<Enter>
imap <S-F2> <ESC>:set syn=sh<Enter>i

" Próximo buffer
map <F6> :n<Enter>
imap <F6> <ESC>:n<Enter>i

" Buffer anterior
map <S-F6> :N<Enter>
imap <S-F6> <ESC>:N<Enter>i

" Indentar linha
map <F8> A<END><DEL><ENTER><ESC>
imap <F8> <END><DEL><ENTER>

" Atualizar Update
map <F10> :diffupdate<ENTER>
imap <F10> <ESC>:diffupdate<ENTER>i

set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = ''
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  silent execute '!diff -awibB ' . opt . '"' . v:fname_in . '" "' . v:fname_new . '" > "' . v:fname_out . '"'
endfunction
